### ISSUE TITLE
DLL load failed while importing hdf5extension

### ISSUE THREAD

**Issue by BadAtComputerGuy** [hemberg-lab/sc3s#8]
Hi Hemberg Lab,

I have an issue when I install sc3s via pip to run alongside scanpy. 

After installing, if I attempt to import scanpy in the script, I get the following new error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5422b1ae3fb8> in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import scanpy as sc
      4 sc.settings.verbosity = 3
      5 sc.settings.set_figure_params(dpi=100, color_map='OrRd')
~\anaconda3\lib\site-packages\scanpy\__init__.py in <module>
     12     # (start with settings as several tools are using it)
     13     from ._settings import settings, Verbosity
---> 14     from . import tools as tl
     15     from . import preprocessing as pp
     16     from . import plotting as pl
~\anaconda3\lib\site-packages\scanpy\tools\__init__.py in <module>
     15 from ._leiden import leiden
     16 from ._louvain import louvain
---> 17 from ._sim import sim
     18 from ._score_genes import score_genes, score_genes_cell_cycle
     19 from ._dendrogram import dendrogram
~\anaconda3\lib\site-packages\scanpy\tools\_sim.py in <module>
     21 from anndata import AnnData
     22 
---> 23 from .. import _utils, readwrite, logging as logg
     24 from .._settings import settings
     25 from .._compat import Literal
~\anaconda3\lib\site-packages\scanpy\readwrite.py in <module>
      8 import pandas as pd
      9 from matplotlib.image import imread
---> 10 import tables
     11 import anndata
     12 from anndata import (
~\anaconda3\lib\site-packages\tables\__init__.py in <module>
     60 # Import the user classes from the proper modules
     61 from .exceptions import *
---> 62 from .file import File, open_file, copy_file
     63 from .node import Node
     64 from .group import Group
~\anaconda3\lib\site-packages\tables\file.py in <module>
     31 import numpy
     32 
---> 33 from . import hdf5extension
     34 from . import utilsextension
     35 from . import parameters
ImportError: DLL load failed while importing hdf5extension: The specified procedure could not be found.
```

I am working with a fresh install of the newest version of anaconda and scanpy.

I have seen on StackOverflow this error can sometimes be resolved by uninstalling and re-installing the tables package. This allowed me to load scanpy again, but when I do a 'b' character is introduced in every member of any dataframe I load, signaling to me an issue with decoding. 

Furthermore, this error with scanpy is not resolved by uninstalling sc3s. The only solution I could find that worked was to uninstall and re-install anaconda from scratch, though a more experienced troubleshooter may have found a simpler one. 

Please let me know if anything can be done to resolve this or if you have any further questions for me.

Thanks

**Comment by QianhuiXu** [comment]
@BadAtComputerGuy 
Hi, I have the same problem when import scanpy.
This my error:
Traceback (most recent call last):
  File "d:/cnv/infercnv.py", line 1, in <module>
    import scanpy as sc
  File "D:\ProgramData\Anaconda3\envs\infercnv\lib\site-packages\scanpy\__init__.py", line 14, in <module>      
    from . import tools as tl
  File "D:\ProgramData\Anaconda3\envs\infercnv\lib\site-packages\scanpy\tools\__init__.py", line 17, in <module>
    from ._sim import sim
  File "D:\ProgramData\Anaconda3\envs\infercnv\lib\site-packages\scanpy\tools\_sim.py", line 23, in <module>    
    from .. import _utils, readwrite, logging as logg
  File "D:\ProgramData\Anaconda3\envs\infercnv\lib\site-packages\scanpy\readwrite.py", line 10, in <module>     
    import tables
  File "D:\ProgramData\Anaconda3\envs\infercnv\lib\site-packages\tables\__init__.py", line 62, in <module>      
    from .file import File, open_file, copy_file
  File "D:\ProgramData\Anaconda3\envs\infercnv\lib\site-packages\tables\file.py", line 33, in <module>
    from . import hdf5extension
ImportError: DLL load failed while importing hdf5extension: 找不到指定的程序。
Please let me know the solution of the problem. Thank you very much!

**Comment by prete** [comment]
This looks like windows, there may be something wrong related to the distribution packages for that OS.
Could you please provide your versions for scanpy/tables/h5py ?  `pip show scanpy h5py tables`

**Comment by CocoGzh** [comment]
> This looks like windows, there may be something wrong related to the distribution packages for that OS. Could you please provide your versions for scanpy/tables/h5py ? `pip show scanpy h5py tables`

Problem has been solved after i reinstall h5py and tables. It can be seen in https://github.com/theislab/scanpy/issues/454 and https://github.com/theislab/scanpy/issues/2108
